# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-06 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ganalytics_obpsorg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('users_num_total', models.BigIntegerField(blank=True, null=True)),
                ('users_num_new', models.BigIntegerField(blank=True, null=True)),
                ('visits_num', models.BigIntegerField(blank=True, null=True)),
                ('countries_num', models.BigIntegerField(blank=True, null=True)),
                ('docs_access_num', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ganalytics_obpsorg',
                'managed': True,
            },
        ),
    ]
