# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-06-16 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conferences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_code', models.TextField(blank=True, null=True)),
                ('activity_name', models.TextField(blank=True, null=True)),
                ('event', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('publisher', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics"."conferences',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Dspace_records',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dspace_object_id', models.TextField(blank=True, null=True)),
                ('handle', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('maturity_level', models.TextField(blank=True, null=True)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('doi', models.TextField(blank=True, null=True)),
                ('doi_obp', models.TextField(blank=True, null=True)),
                ('submitter_id', models.TextField(blank=True, null=True)),
                ('publisher_place', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('year_created', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics"."dspace_records',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Dspace_collections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics"."dspace_collections',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Dspace_communities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics"."dspace_communities',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Dspace_record_disciplines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dspace_object_id', models.TextField(blank=True, null=True)),
                ('discipline_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics"."dspace_record_disciplines',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Dspace_record_bptypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dspace_object_id', models.TextField(blank=True, null=True)),
                ('bp_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics"."dspace_record_bptypes',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Dspace_record_adoptiontypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dspace_object_id', models.TextField(blank=True, null=True)),
                ('adoption_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics"."dspace_record_adoptiontypes',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Dspace_record_eovs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dspace_object_id', models.TextField(blank=True, null=True)),
                ('eov', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics"."dspace_record_eovs',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Dspace_record_sdgs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dspace_object_id', models.TextField(blank=True, null=True)),
                ('sdg', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics"."dspace_record_sdgs',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('list_name', models.TextField(blank=True, null=True)),
                ('subject_line', models.TextField(blank=True, null=True)),
                ('emails_sent', models.IntegerField(blank=True, null=True)),
                ('unsubscribed', models.IntegerField(blank=True, null=True)),
                ('hard_bounces', models.IntegerField(blank=True, null=True)),
                ('soft_bounces', models.IntegerField(blank=True, null=True)),
                ('opens_total', models.IntegerField(blank=True, null=True)),
                ('unique_opens', models.IntegerField(blank=True, null=True)),
                ('clicks_total', models.IntegerField(blank=True, null=True)),
                ('unique_clicks', models.IntegerField(blank=True, null=True)),
                ('unique_subscriber_clicks', models.IntegerField(blank=True, null=True)),

            ],
            options={
                'db_table': 'metrics"."newsletter',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Newsletter_subscribers_grouth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('subscribed', models.IntegerField(blank=True, null=True)),
                ('list_change_mom', models.IntegerField(blank=True, null=True)),
                ('list_change_yoy', models.IntegerField(blank=True, null=True)),

            ],
            options={
                'db_table': 'metrics"."newsletter_subscribers_grouth',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Newsletter_locations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.TextField(blank=True, null=True)),
                ('cc', models.TextField(blank=True, null=True)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),

            ],
            options={
                'db_table': 'metrics"."newsletter_locations',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Communities_engagement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('user_community', models.TextField(blank=True, null=True)),
                ('contacts', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('lead', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'metrics"."communities_engagement',
                'managed': True,
            },
        ),

        migrations.CreateModel(
            name='Obps_workshops',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('country_celebration', models.TextField(blank=True, null=True)),
                ('num_participants', models.IntegerField(blank=True, null=True)),
                ('num_participants_countries_origin', models.IntegerField(blank=True, null=True)),
                ('num_support_organizations', models.IntegerField(blank=True, null=True)),

            ],
            options={
                'db_table': 'metrics"."obps_workshops',
                'managed': True,
            },
        ),
    ]


# DROP TABLE metrics.newsletter, metrics.newsletter_subscribers_grouth, metrics.newsletter_locations, metrics.conferences, metrics.dspace_collections, metrics.dspace_communities, metrics.dspace_record_adoptiontypes, metrics.dspace_record_bptypes, metrics.dspace_record_disciplines, metrics.dspace_records, metrics.dspace_record_eovs, metrics.dspace_record_sdgs, metrics.communities_engagement,metrics.obps_workshops
